# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'ui', 'classify_image']

# %% app.ipynb 2
from fastai.vision.all import *
import gradio as gr

# %% app.ipynb 4
learn = load_learner("export.pkl")

# %% app.ipynb 5
categories = ("da vinci", "titian", "michelangelo", "raphael")

def classify_image(img):
    prediction, index, probability = learn.predict(img)
    return dict(zip(categories, map(float, probability)))

# %% app.ipynb 7
image = gr.Image(height=192, width=192)
label = gr.Label()
examples = ["da-vinci.jpg", "titian.jpg", "michelangelo.jpg", "raphael.jpg"]

ui = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
ui.launch()
